<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>design-mode-demo</module>
        <module>spring-boot-demo</module>
        <module>spring-cloud-alibaba-demo</module>
        <module>spring-rabbitmq-demo</module>
        <module>spring-zookeeper-kafka-demo</module>
        <module>spring-sentinel-core-demo</module>
        <module>spring-cloud-gateway-demo</module>
        <module>spring-boot-redis-demo</module>
        <module>spring-boot-data-demo</module>
        <module>spring-boot-mp-demo</module>
    </modules>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.9</version>
    </parent>

    <name>SpringAwesome</name>

    <groupId>com.example</groupId>
    <artifactId>spring-awesome</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>3.5.12</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter-test</artifactId>
                <version>3.5.12</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>